import { z } from "zod";

/**
 * Output schema for the news prompt template.
 *
 * response_format: none — Sonar Pro returns free text for long articles.
 * Zod validates the structure after parsing.
 *
 * Note: markdownText holds the full article body.
 * slug is generated by the AI as a URL-friendly identifier.
 */
export default z.object({
  title: z.string(),
  slug: z.string(),
  language: z.string(),
  seoMetaDescription: z.string(),
  markdownText: z.string(),
  imageHints: z.object({
    searchQueries: z.array(z.string()),
    suggestedAlt: z.string(),
  }),
});
